config/routes.rb
Rails.application.routes.draw do
  get 'projects/new'

  get 'projects/index'

  get 'projects/edit'
  get "dashboard"=> 'todos#index'
  get "user" =>'users#dashboard'
  get "task" =>'todos#task'
  get "task-wait"=>"todos#task_wait"
  post "todos/done"
  root :to => 'home#index'
  devise_for :users ,:controllers => { :registrations => "registrations",:sessions=>"sessions"}
  devise_for :admin ,:controllers => { :registrations => "registrations",:sessions=>"sessions"}
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  scope "/admin" do
    resources :projects
  end

end

app/controllers/home_controller.rb
###
# Home Controller For Display Application Hompage
###
class HomeController < ApplicationController
  # before_action :authenticate_user!
  def index
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<%=content_tag :div,class:"container " do %>
  <%=content_tag :div,class:"page-header " do %>
    <%= content_tag(:h2,"Project Managment Todo Application",class:"text-center")%>
  <% end %>

  <%=content_tag :div,class:"row" do %>
      <%=content_tag :div,class:"col-md-6 " do %>
        <%= image_tag( "/images/todo.png",align:"center") %>
      <% end %>

      <%=content_tag :div,class:"col-md-6 " do %>
        <% unless user_signed_in?%>
          <%= link_to new_user_session_path do %>
            <%=content_tag :button ,"User Login", class:"btn-info btn-lg btn-block",style:"margin-bottom:1%;margin-top:30%"%>
            <% end %>
          <% end %>
          <% unless admin_signed_in?%>
            <%= link_to new_admin_session_path do %>
              <%=content_tag :button ,"Admin Login", class:"btn-warning btn-lg btn-block"%>
            <% end %>
          <% end %>
        <% end %>
    <% end %>
<% end %>